import { PageSchema } from "@/components/constructor/page-render/types";
import {
    COMPANY_NAME,
    COMPANY_ADDRESS,
    COMPANY_PHONE,
    COMPANY_LEGAL_NAME,
    COMPANY_NUMBER,
    COMPANY_EMAIL,
} from "@/resources/constants";

const privacyPolicySchema: PageSchema = {
    meta: {
        title: `Privacy Policy – ${COMPANY_NAME}`,
        description:
            `${COMPANY_NAME} Privacy Policy: details on what data we collect, how we use it, retention, transfers, and your rights under UK GDPR.`,
        keywords: [
            "privacy policy",
            "GDPR",
            "data protection",
            "esim",
            "aries sim",
            "personal data",
            "uk gdpr",
            "tokens",
        ],
        canonical: "/privacy-policy",
        ogImage: {
            title: `${COMPANY_NAME} – Privacy Policy`,
            description:
                `Transparent privacy practices for ${COMPANY_NAME} under UK GDPR.`,
            bg: "#ffffff",
            color: "#000000",
        },
    },
    blocks: [
        {
            type: "text",
            title: "Privacy Policy",
            description:
                `Effective date: 7 April 2026\n\nThis Privacy Policy explains how ${COMPANY_LEGAL_NAME} (“we”, “us”, “our”) collects, uses, shares, stores, and protects personal data when you use Aries Sim and related services available at https://www.ariessim.co.uk (the “Service”).\n\nData Controller\n${COMPANY_LEGAL_NAME}\nCompany Number: ${COMPANY_NUMBER}\nAddress: ${COMPANY_ADDRESS}\nEmail: ${COMPANY_EMAIL}\nPhone: ${COMPANY_PHONE}\n\nThis Privacy Policy applies to personal data collected through the website, account registration, login areas, balance and Token purchases, checkout, eSIM purchases, digital delivery, customer support, and related service operations.`,
        },
        {
            type: "text",
            title: "1. General Principles",
            bullets: [
                "1.1 We process personal data in accordance with the UK GDPR, the Data Protection Act 2018, and other applicable data protection laws.",
                "1.2 We collect and use only the personal data that is reasonably necessary for legitimate business purposes, including providing the Service, managing accounts, processing payments, delivering eSIM Plans, responding to enquiries, ensuring platform security, preventing fraud, and complying with legal obligations.",
                "1.3 By using the Service, you acknowledge that your personal data will be processed as described in this Privacy Policy.",
            ],
        },
        {
            type: "text",
            title: "2. Personal Data We Collect",
            description:
                "Depending on how you use the Service, we may collect the following categories of personal data:",
            bullets: [
                "2.1 Identity and contact data",
                "This may include:",
                "• name;",
                "• email address;",
                "• billing name;",
                "• billing address;",
                "• country or destination information;",
                "• phone number, where provided.",
                "2.2 Account data",
                "This may include:",
                "• account login details;",
                "• hashed password and authentication-related records;",
                "• account preferences;",
                "• profile information;",
                "• Balance and Token records;",
                "• account status;",
                "• account creation and login history.",
                "2.3 Order and transaction data",
                "This may include:",
                "• order references;",
                "• purchase history;",
                "• Token purchases and redemptions;",
                "• eSIM Plan purchases;",
                "• transaction dates;",
                "• payment status;",
                "• currency used;",
                "• refund, reversal, and chargeback information;",
                "• payment processor references;",
                "• limited payment metadata provided by payment processors, such as card brand or masked card details where available.",
                "We do not store full payment card numbers or card security codes on our own servers. Payment transactions are handled by third-party payment providers.",
                "2.4 Service and usage data",
                "This may include:",
                "• selected eSIM Plans;",
                "• selected destination, region, duration, and data allowance;",
                "• delivery status;",
                "• activation-related records;",
                "• plan access history;",
                "• dashboard interaction history;",
                "• timestamps and activity logs;",
                "• records of Token deductions linked to requested services.",
                "2.5 Device and technical support data",
                "Where relevant to delivery, activation, or support, we may collect information such as:",
                "• device model;",
                "• operating system;",
                "• eSIM compatibility details you provide;",
                "• network unlock status, where you disclose it;",
                "• screenshots, error messages, or troubleshooting details you choose to share;",
                "• installation or activation issue descriptions.",
                "2.6 Technical data",
                "This may include:",
                "• IP address;",
                "• browser type and version;",
                "• operating system;",
                "• device information;",
                "• language settings;",
                "• time zone;",
                "• referral data;",
                "• cookies and similar technologies;",
                "• diagnostic logs and security event data.",
                "2.7 Communications and support data",
                "This may include:",
                "• emails;",
                "• support tickets;",
                "• contact form messages;",
                "• complaint correspondence;",
                "• refund request information;",
                "• attachments or screenshots you choose to provide.",
                "2.8 Marketing and consent data",
                "Where relevant, this may include:",
                "• newsletter preferences;",
                "• marketing opt-in records;",
                "• consent timestamps;",
                "• unsubscribe records;",
                "• campaign interaction data.",
            ],
        },
        {
            type: "text",
            title: "3. How We Collect Personal Data",
            bullets: [
                "We collect personal data:",
                "• directly from you, when you create an Account, buy Tokens, purchase or redeem an eSIM Plan, contact support, submit a form, or otherwise use the Service;",
                "• automatically, through cookies, logs, analytics tools, and technical monitoring when you use the website or platform;",
                "• from payment processors and service providers, for example where they confirm payment, fraud checks, refunds, or transaction status;",
                "• from technical or fulfilment partners where reasonably necessary to deliver, troubleshoot, secure, or support the Service.",
            ],
        },
        {
            type: "text",
            title: "4. How and Why We Use Personal Data",
            description:
                "We process personal data only where we have a valid legal basis under applicable law.",
            bullets: [
                "4.1 Performance of a contract",
                "We process personal data where necessary to:",
                "• create and manage your Account;",
                "• provide access to the Service;",
                "• process Token purchases;",
                "• manage Balance and Token records;",
                "• process eSIM Plan purchases and redemptions;",
                "• deliver eSIM Plans digitally;",
                "• provide customer support;",
                "• manage refunds, payment disputes, cancellations, and account-related matters.",
                "4.2 Compliance with legal obligations",
                "We process personal data where necessary to:",
                "• comply with tax, accounting, and financial reporting obligations;",
                "• comply with consumer protection obligations;",
                "• respond to lawful requests from authorities;",
                "• keep records required by law;",
                "• comply with payment, fraud-prevention, and chargeback-handling obligations.",
                "4.3 Legitimate interests",
                "We may process personal data where necessary for our legitimate interests, provided those interests are not overridden by your rights and freedoms. These interests may include:",
                "• operating, administering, and improving the Service;",
                "• fraud prevention and payment security;",
                "• account and platform security;",
                "• enforcing our Terms and policies;",
                "• handling complaints and disputes;",
                "• internal reporting, troubleshooting, and service analytics;",
                "• preventing abuse, misuse, or unauthorised activity;",
                "• protecting our legal rights, suppliers, and business operations.",
                "4.4 Consent",
                "We rely on consent where required, including:",
                "• sending marketing communications where applicable; and",
                "• placing non-essential cookies or similar technologies where required by law.",
                "You may withdraw consent at any time, but this will not affect the lawfulness of processing carried out before withdrawal.",
                "4.5 Establishment, exercise, or defence of legal claims",
                "Where necessary, we may process personal data in connection with disputes, complaints, chargebacks, legal claims, regulatory matters, or enforcement of our rights.",
            ],
        },
        {
            type: "text",
            title: "5. Special Category Data",
            bullets: [
                "5.1 We do not intentionally require special category personal data in order for you to browse the website, create an Account, purchase Tokens, or buy an eSIM Plan.",
                "5.2 Please do not send us unnecessary sensitive personal data, such as health information, unless it is strictly relevant to a support issue and you choose to provide it.",
                "5.3 If sensitive personal data is nevertheless provided to us, we will process it only where permitted by law and only to the extent reasonably necessary for the relevant support, legal, or compliance purpose.",
            ],
        },
        {
            type: "text",
            title: "6. Cookies and Similar Technologies",
            bullets: [
                "6.1 We use cookies and similar technologies, including local storage and session storage, to operate the Service, maintain login sessions, remember preferences, improve performance, protect accounts, and understand how users interact with the website.",
                "6.2 Some cookies are strictly necessary for the website or platform to function and do not require consent under applicable law.",
                "6.3 Other cookies or similar technologies, such as analytics or marketing tools, may be used only where the required consent has been obtained.",
                "6.4 Further information is provided in our Cookie Policy.",
            ],
        },
        {
            type: "text",
            title: "7. How We Share Personal Data",
            description:
                "We do not sell your personal data. We may share personal data only where reasonably necessary, including with:",
            bullets: [
                "7.1 Payment service providers",
                "To process payments, payment verification, fraud screening, refunds, reversals, and payment-related investigations.",
                "7.2 Hosting, infrastructure, and technology providers",
                "To host, maintain, secure, and operate the website, platform, storage systems, databases, authentication systems, and communications tools.",
                "7.3 Telecom, network, and fulfilment partners",
                "To provision, deliver, activate, support, replace, or troubleshoot eSIM Plans and related connectivity services.",
                "7.4 Analytics, communications, and support providers",
                "To help us understand usage, manage support, send service messages, monitor security, and improve operations.",
                "7.5 Professional advisers and business service providers",
                "Including legal advisers, accountants, auditors, insurers, consultants, and payment dispute advisers where necessary for legitimate business or legal purposes.",
                "7.6 Authorities and law enforcement",
                "Where disclosure is required by law, court order, regulatory requirement, or where necessary to protect legal rights, investigate fraud, respond to chargebacks, or prevent unlawful conduct.",
                "7.7 Business transfers",
                "If we are involved in a merger, acquisition, restructuring, financing transaction, asset sale, or similar corporate transaction, personal data may be disclosed as part of that process subject to appropriate confidentiality and legal safeguards.",
            ],
        },
        {
            type: "text",
            title: "8. International Transfers",
            bullets: [
                "8.1 Some service providers or fulfilment partners may process personal data outside the UK or outside the country where you are located.",
                "8.2 Where personal data is transferred internationally, we take reasonable steps to ensure that appropriate safeguards are in place, such as:",
                "• transfers to countries recognised as providing an adequate level of protection;",
                "• use of the UK International Data Transfer Agreement, the UK Addendum, or Standard Contractual Clauses where appropriate; or",
                "• other lawful transfer mechanisms recognised under applicable data protection law.",
                "8.3 You may contact us if you would like more information about the safeguards used for relevant international transfers.",
            ],
        },
        {
            type: "text",
            title: "9. Data Retention",
            bullets: [
                "9.1 We retain personal data only for as long as reasonably necessary for the purposes for which it was collected, including for legal, accounting, tax, fraud prevention, consumer protection, payment dispute, telecom support, and record-keeping purposes.",
                "9.2 Retention periods may vary depending on the nature of the data and the reason for processing. In general:",
                "• Account data is kept while your Account remains active and for a reasonable period afterwards;",
                "• Balance, Token, order, delivery, activation, and support records may be retained while required to operate your Account, resolve disputes, or maintain business records;",
                "• transaction, payment, refund, and chargeback records may be kept for several years where required for legal, tax, accounting, fraud prevention, or dispute purposes;",
                "• support correspondence is kept for as long as reasonably necessary to manage the matter and maintain appropriate records;",
                "• technical logs are retained for a limited period unless longer retention is required for security or investigation purposes;",
                "• marketing data is retained until you withdraw consent or object, except where limited suppression records must be kept to respect your preferences.",
                "9.3 When personal data is no longer required, we will delete, anonymise, or securely archive it in accordance with applicable law and internal retention practices.",
            ],
        },
        {
            type: "text",
            title: "10. Your Rights",
            bullets: [
                "Under applicable data protection law, you may have the right to:",
                "• access the personal data we hold about you;",
                "• rectify inaccurate or incomplete personal data;",
                "• erase your personal data in certain circumstances;",
                "• restrict the processing of your personal data in certain circumstances;",
                "• object to processing based on legitimate interests, including direct marketing;",
                "• withdraw consent where processing is based on consent;",
                "• receive portability of certain personal data in a structured, commonly used, machine-readable format, where applicable;",
                "• lodge a complaint with the Information Commissioner’s Office (ICO) or another competent supervisory authority.",
                `To exercise your rights, contact us at ${COMPANY_EMAIL}. We may request reasonable proof of identity before acting on your request.`,
                "We will respond within the time periods required by applicable law. Some rights are not absolute and may be limited where we have overriding legal grounds or are required to retain certain data.",
            ],
        },
        {
            type: "text",
            title: "11. Marketing Communications",
            bullets: [
                "11.1 We may send you service-related communications necessary for your Account, Orders, payments, Balance or Token records, digital delivery, security notices, or support matters.",
                "11.2 Where marketing consent is required, we will send promotional communications only if you have opted in or where another lawful basis applies under applicable law.",
                "11.3 You may unsubscribe from marketing emails at any time by using the unsubscribe link or by contacting us directly.",
                "11.4 Even if you opt out of marketing, we may still send essential service or transactional communications.",
            ],
        },
        {
            type: "text",
            title: "12. Security",
            bullets: [
                "12.1 We implement reasonable technical and organisational measures designed to protect personal data against unauthorised access, loss, misuse, alteration, or disclosure.",
                "12.2 Such measures may include access controls, encryption in transit where appropriate, credential protections, logging, secure hosting practices, role-based access restrictions, and backup procedures.",
                "12.3 No system is completely secure, and we cannot guarantee absolute security. You are also responsible for maintaining the confidentiality of your Account credentials.",
            ],
        },
        {
            type: "text",
            title: "13. Children",
            bullets: [
                "13.1 The Service is not intended for persons under the age of 18.",
                "13.2 We do not knowingly collect personal data from children.",
                `13.3 If you believe that personal data of a child has been provided to us, please contact us at ${COMPANY_EMAIL}, and we will take appropriate steps to investigate and, where appropriate, delete the data.`,
            ],
        },
        {
            type: "text",
            title: "14. Automated Processing",
            bullets: [
                "14.1 We may use automated tools for fraud prevention, payment verification, account security, service monitoring, and operational administration of the Service.",
                "14.2 We do not currently intend to make decisions based solely on automated processing that produce legal effects or similarly significant effects on you without appropriate safeguards and notice where required by law.",
            ],
        },
        {
            type: "text",
            title: "15. Changes to This Privacy Policy",
            bullets: [
                "15.1 We may update this Privacy Policy from time to time for legal, regulatory, technical, operational, supplier-related, or commercial reasons.",
                "15.2 The latest version will be published on the Service with the updated effective date.",
                "15.3 Where changes are material, we may provide additional notice through the website, your Account, or by email where appropriate.",
            ],
        },
        {
            type: "text",
            title: "16. Contact and Complaints",
            description:
                "If you have any questions about this Privacy Policy or wish to exercise your rights, please contact:",
            bullets: [
                COMPANY_LEGAL_NAME || "",
                `Company Number: ${COMPANY_NUMBER}`,
                `Address: ${COMPANY_ADDRESS}`,
                `Email: ${COMPANY_EMAIL}`,
                `Phone: ${COMPANY_PHONE}`,
            ],
        },
    ],
};

export default privacyPolicySchema;