import { PageSchema } from "@/components/constructor/page-render/types";

const termsSchema: PageSchema = {
    meta: {
        title: "Terms and Conditions – Aries Sim",
        description:
            "Official Terms and Conditions for using Aries Sim – account, balance, tokens, eSIM plans, payments, refunds, liability, and user rights.",
        keywords: [
            "terms and conditions",
            "aries sim",
            "esim",
            "tokens",
            "balance",
            "refunds",
            "digital delivery",
            "mobile data",
        ],
        canonical: "/terms-and-conditions",
        ogImage: {
            title: "Aries Sim – Terms and Conditions",
            description: "Full Terms and Conditions for Aries Sim eSIM platform.",
            bg: "#ffffff",
            color: "#000000",
        },
    },
    blocks: [
        {
            type: "text",
            title: "Terms and Conditions",
            description:
                "Effective date: 7 April 2026\n\nThese Terms and Conditions (“Terms”) govern your access to and use of the Aries Sim website, platform, account area, balance system, checkout flow, dashboard, and related digital eSIM services available at https://www.ariessim.co.uk (the “Service”).\n\nThe Service is operated by:\nARIES ACCESSIBILITY LTD\nCompany Number: 15588986\nAddress: 20 Wenlock Road, London, England, N1 7GU\nEmail: info@ariessim.co.uk\nPhone: +44 7418 636626\n\nThroughout these Terms, “Company”, “we”, “us”, and “our” refer to ARIES ACCESSIBILITY LTD. “You” and “your” refer to the person or entity using the Service.\n\nBy accessing or using the Service, creating an account, topping up balance, purchasing Tokens, redeeming Tokens, purchasing or activating an eSIM Plan, or otherwise placing an Order through the Service, you agree to be bound by these Terms. If you do not agree, you must not use the Service.",
        },
        {
            type: "text",
            title: "1. Definitions",
            description: "For the purposes of these Terms:",
            bullets: [
                "Account means your registered user account on the Service.",
                "Balance means the prepaid value recorded in your Account and available for use within the Service.",
                "Tokens means the internal prepaid digital credits used within the Service to purchase or redeem eSIM Plans and related digital services. Tokens are an internal accounting mechanism only.",
                "eSIM means a digital SIM profile that may be installed on a compatible device without a physical SIM card.",
                "eSIM Plan means a digital mobile connectivity package made available through the Service, which may include a specified destination, region, coverage area, duration, data allowance, activation rules, and other plan-specific conditions.",
                "Digital Delivery means electronic delivery of an eSIM, QR code, activation code, installation details, or related instructions by email, through your Account, or through another digital method designated by us.",
                "Order means a completed purchase of Tokens, a completed purchase or redemption of an eSIM Plan, or another paid transaction through the Service.",
                "Services means all products, plans, features, content, functionality, support tools, and related digital services made available through the Service.",
                "Supported Device means a device that is eSIM-compatible, network-unlocked where required, and otherwise technically suitable for the selected eSIM Plan.",
            ],
        },
        {
            type: "text",
            title: "2. Eligibility and Account Registration",
            bullets: [
                "2.1 You must be at least 18 years old to use the Service and create an Account.",
                "2.2 If you use the Service on behalf of a company or other legal entity, you represent and warrant that you have authority to bind that entity to these Terms.",
                "2.3 You must provide accurate, current, and complete information when creating an Account, placing an Order, topping up your Balance, or contacting support.",
                "2.4 You are responsible for maintaining the confidentiality of your login credentials and for all activity carried out through your Account.",
                "2.5 You must promptly notify us at info@ariessim.co.uk if you suspect unauthorised access to your Account or any other security breach.",
                "2.6 We may refuse registration, request verification, suspend an Account, restrict access, or place limits on use where reasonably necessary for security, fraud prevention, abuse prevention, payment integrity, legal compliance, or operational reasons.",
            ],
        },
        {
            type: "text",
            title: "3. Nature of the Service",
            bullets: [
                "3.1 Aries Sim is a digital eSIM marketplace through which users may top up Balance, purchase Tokens, and use those Tokens to obtain eSIM Plans and related digital services.",
                "3.2 The Service is provided digitally only. Unless expressly stated otherwise, we do not sell or deliver physical SIM cards or other physical goods.",
                "3.3 eSIM Plans made available through the Service may be country-specific, regional, or global, and may vary by price, duration, data allowance, supported networks, activation method, and other plan-specific conditions.",
                "3.4 The Service may rely on third-party carriers, telecom infrastructure providers, aggregators, payment processors, technical partners, and email or hosting providers.",
                "3.5 We may change, update, improve, limit, suspend, remove, or discontinue any part of the Service at any time for legal, technical, security, operational, supplier-related, or commercial reasons.",
                "3.6 We do not guarantee that every destination, region, price, plan type, supported network, currency, feature, or promotional offer will remain available at all times.",
            ],
        },
        {
            type: "text",
            title: "4. Balance and Tokens",
            bullets: [
                "4.1 Tokens are prepaid internal digital credits used solely within the Service.",
                "4.2 Tokens are not legal tender, electronic money, payment instruments, bank deposits, investments, securities, or cryptoassets.",
                "4.3 Tokens:",
                "(a) do not accrue interest;",
                "(b) have no cash value outside the Service;",
                "(c) cannot be withdrawn as cash;",
                "(d) are not transferable unless we expressly agree otherwise in writing; and",
                "(e) cannot be resold, assigned, pledged, or exchanged outside the Service.",
                "4.4 Purchased Tokens are credited to your Account after successful payment authorisation and processing.",
                "4.5 Tokens are deducted when you purchase or redeem an eSIM Plan or when performance of the relevant digital service begins.",
                "4.6 Unless expressly stated otherwise on the Service, purchased Tokens do not expire while your Account remains open and in good standing. This does not limit our right to adjust, reverse, or remove Token balances affected by chargeback, payment reversal, fraud, abuse, manifest error, duplicate crediting, unauthorised activity, or legal obligation.",
                "4.7 We may offer promotional, bonus, goodwill, or trial Tokens. Unless expressly stated otherwise, such Tokens are non-refundable, non-transferable, and may be subject to separate conditions, limitations, or expiry periods.",
                "4.8 We reserve the right to correct Token balances affected by manifest error, technical malfunction, fraud, abuse, duplicate crediting, payment reversal, or unauthorised activity.",
            ],
        },
        {
            type: "text",
            title: "5. Payment, Pricing, and Billing Terms",
            bullets: [
                "5.1 Prices, Token packages, supported currencies, and payment methods are those displayed on the Service or at checkout at the time of your Order.",
                "5.2 The price payable for your Order is the price shown to you at checkout before you confirm payment. Any taxes, if applicable, will be shown as required before completion of the transaction.",
                "5.3 Your bank, card issuer, or payment provider may apply foreign transaction fees, currency conversion spreads, or other third-party charges outside our control. We are not responsible for such charges.",
                "5.4 By submitting payment details, you represent and warrant that:",
                "(a) you are authorised to use the selected payment method;",
                "(b) the payment information provided is accurate and complete; and",
                "(c) there are sufficient funds or credit available to complete the transaction.",
                "5.5 All payments are subject to authorisation, screening, and verification by us and/or our third-party payment processors.",
                "5.6 We may decline, hold, or cancel an Order where reasonably necessary for fraud prevention, payment security, abuse prevention, legal compliance, supplier restrictions, or operational reasons.",
                "5.7 If a payment is declined, reversed, charged back, disputed without valid basis, or later found to be unauthorised, we may:",
                "(a) refuse or reverse the relevant Token credit;",
                "(b) suspend or restrict your Account;",
                "(c) withhold pending delivery;",
                "(d) revoke access to undelivered or improperly obtained Services to the extent permitted by law; and/or",
                "(e) take reasonable recovery steps.",
                "5.8 You must contact us promptly if you believe you have been charged incorrectly. We may require reasonable supporting information to investigate and resolve the issue.",
            ],
        },
        {
            type: "text",
            title: "6. Orders and Digital Delivery",
            bullets: [
                "6.1 General Order Terms",
                "6.1.1 All Orders are subject to our acceptance.",
                "6.1.2 An Order for Tokens is placed when you complete checkout and your payment is successfully authorised and processed.",
                "6.1.3 An Order for an eSIM Plan is placed when:",
                "(a) you have sufficient Tokens or otherwise complete the required payment step;",
                "(b) you select the relevant eSIM Plan; and",
                "(c) you confirm the purchase or redemption through the Service.",
                "6.1.4 We may refuse, cancel, reverse, or place an Order on hold where reasonably necessary, including in cases of suspected fraud, payment issues, inaccurate information, technical errors, supplier rejection, abuse, legal compliance requirements, or inability to fulfil the Order.",
                "6.2 Delivery of Tokens",
                "6.2.1 Purchased Tokens are normally credited electronically to your Account shortly after successful payment confirmation.",
                "6.2.2 If Token crediting is delayed due to a technical issue attributable to us, we will use reasonable efforts to correct the issue within a reasonable period.",
                "6.3 Delivery of eSIM Plans",
                "6.3.1 All eSIM Plans are delivered digitally only.",
                "6.3.2 Delivery may be made by email, through your Account, through your dashboard, or by another digital method designated on the Service.",
                "6.3.3 Delivery may include, as applicable, a QR code, manual activation code, installation details, setup instructions, and plan information.",
                "6.3.4 Delivery times shown on the Service are estimates unless we expressly state otherwise.",
                "6.3.5 An eSIM Plan is deemed delivered when the relevant QR code, activation details, installation details, or access credentials have been sent to the email address associated with your Order, made available in your Account, or otherwise made electronically available to you.",
                "6.3.6 You are responsible for providing a correct email address, checking your inbox and spam folder, maintaining access to your Account, and ensuring you can receive Digital Delivery.",
                "6.3.7 We are not responsible for delivery problems caused by incorrect contact information supplied by you, email filtering outside our control, user-side device restrictions, or your inability to access your email or Account.",
            ],
        },
        {
            type: "text",
            title: "7. eSIM Plan Conditions, Compatibility, and Activation",
            bullets: [
                "7.1 Each eSIM Plan is subject to the plan-specific details shown on the applicable product page or provided at delivery, including destination coverage, duration, data allowance, validity period, activation rules, supported networks, and any fair use or technical limitations.",
                "7.2 Unless expressly stated otherwise, you should not assume that an eSIM Plan includes voice calls, SMS, a local phone number, tethering, hotspot use, or support for all devices or all network features.",
                "7.3 You are solely responsible for confirming before purchase that:",
                "(a) your device is eSIM-compatible;",
                "(b) your device is network-unlocked where required;",
                "(c) your device supports the relevant technical specifications for the selected plan; and",
                "(d) the selected eSIM Plan is suitable for your intended destination and travel dates.",
                "7.4 You are responsible for following installation and activation instructions correctly. Incorrect installation, premature activation, activation on the wrong device, deletion of the eSIM profile, device reset, or other user-side handling may make reinstallation, recovery, or reuse impossible, depending on supplier and network rules.",
                "7.5 Some eSIM Plans may start their validity period upon installation, upon first activation, upon first connection to a supported network, or in another manner stated on the product page or in delivery instructions. You are responsible for reviewing those rules before purchase and activation.",
                "7.6 Coverage, speed, latency, network technology, and service quality may vary by location, device, terrain, buildings, local network congestion, government restrictions, maintenance, third-party carrier performance, and other factors outside our reasonable control.",
                "7.7 We do not guarantee uninterrupted connectivity, continuous coverage, minimum speeds, or that the Service will function identically in every country, region, or location within a covered destination.",
                "7.8 Unless expressly stated otherwise, eSIM Plans are not intended to be relied upon as your sole means of emergency communication, and may not support emergency calling or emergency SMS.",
                "7.9 You are responsible for managing your own device settings, including which SIM is used for data, roaming settings, and the status of your primary physical SIM or home carrier plan. We are not responsible for charges imposed by your mobile carrier because your main SIM remained active, roaming was enabled, or device settings were not configured correctly.",
            ],
        },
        {
            type: "text",
            title: "8. Cancellation Rights and Refund Terms",
            bullets: [
                "8.1 Nothing in these Terms limits any mandatory consumer rights that apply to you under applicable law.",
                "8.2 Token Purchases",
                "8.2.1 If you are a consumer and purchase Tokens, you may have a statutory right to cancel that purchase within 14 days from the date of purchase, provided that the relevant Tokens have not been used, redeemed, spent, consumed, or mixed with promotional or bonus credits in a way that makes separation impracticable.",
                "8.2.2 Where cancellation is validly exercised for unused purchased Tokens, we will refund the relevant amount to the original payment method within the period required by applicable law.",
                "8.2.3 Promotional, bonus, trial, or goodwill Tokens are not cash purchases and are not refundable unless required by law.",
                "8.3 eSIM Plans and Immediate Digital Supply",
                "8.3.1 By purchasing or redeeming Tokens for an eSIM Plan and requesting Digital Delivery, you expressly request immediate performance of a digital service and immediate supply of digital content.",
                "8.3.2 To the extent permitted by applicable law, you acknowledge that once delivery has begun, the QR code or activation details have been issued, or the eSIM Plan has been provisioned for your Order, your statutory withdrawal or cancellation right may be lost.",
                "8.3.3 Performance is treated as having begun once the eSIM, QR code, activation details, installation details, or comparable digital access credentials have been generated, allocated, or made available to you.",
                "8.4 Refund Rules",
                "8.4.1 Used or redeemed Tokens and delivered eSIM Plans are non-refundable except:",
                "(a) where required by applicable law;",
                "(b) where we fail to provide the purchased Service;",
                "(c) where the eSIM Plan is materially defective and we cannot correct, replace, or re-deliver it within a reasonable period; or",
                "(d) where we expressly agree otherwise.",
                "8.4.2 Refunds are not available merely because:",
                "(a) you changed your mind after delivery or performance began;",
                "(b) you purchased the wrong destination, duration, or data allowance;",
                "(c) your travel plans changed or were cancelled;",
                "(d) your device was not compatible, not unlocked, not updated, or otherwise unsuitable;",
                "(e) you activated the plan earlier than intended;",
                "(f) you deleted the eSIM profile, reset the device, changed device, or otherwise lost access through user-side actions;",
                "(g) local signal quality, coverage quality, or speed was lower than you hoped, where the plan was otherwise substantially as described;",
                "(h) you failed to configure your device correctly or follow installation instructions; or",
                "(i) charges were incurred from your primary carrier because your own SIM settings were not managed correctly.",
                "8.4.3 If you believe Tokens were deducted incorrectly, delivery failed, or an eSIM Plan is not functioning due to a technical issue attributable to us or our supplier, you must contact us promptly at info@ariessim.co.uk and provide sufficient details for review, including the relevant Order details, device model, destination, and a description of the issue.",
                "8.4.4 Where a technical or fulfilment issue is attributable to us or to a supplier acting within the fulfilment chain, we may, at our discretion and where appropriate, re-deliver the eSIM, correct the issue, restore the relevant Tokens, replace the plan, or provide a refund.",
                "8.4.5 Refunds, where approved, will ordinarily be made to the original payment method unless otherwise required by law.",
                "8.4.6 Our separate Refund Policy may provide additional detail, but if there is a conflict between that policy and mandatory law, mandatory law prevails.",
            ],
        },
        {
            type: "text",
            title: "9. User Responsibilities and Acceptable Use",
            bullets: [
                "9.1 You are solely responsible for all information, destination selections, device information, and instructions submitted by you through the Service.",
                "9.2 You represent and warrant that your use of the Service and any information you submit:",
                "(a) is accurate and not misleading to the best of your knowledge;",
                "(b) is lawful;",
                "(c) does not infringe third-party rights; and",
                "(d) does not contain malicious or harmful code.",
                "9.3 You must not use the Service:",
                "(a) unlawfully or fraudulently;",
                "(b) to submit false or misleading information;",
                "(c) to interfere with the operation, security, or integrity of the Service;",
                "(d) to gain unauthorised access to accounts, systems, or data;",
                "(e) to scrape, reverse engineer, copy, extract, or exploit the Service without authorisation;",
                "(f) to resell, redistribute, share, or commercially exploit Tokens, eSIM Plans, QR codes, activation codes, or setup instructions without our prior written consent;",
                "(g) to abuse promotional offers, support channels, chargeback processes, or Token mechanisms; or",
                "(h) in a way that could damage our reputation, infrastructure, supplier relationships, or legal position.",
            ],
        },
        {
            type: "text",
            title: "10. Third-Party Networks and External Services",
            bullets: [
                "10.1 The Service may use or depend on third-party carriers, network operators, telecom providers, aggregators, payment processors, hosting providers, analytics tools, communication tools, and other external service providers.",
                "10.2 We do not control third-party networks or third-party services and are not responsible for their independent acts, omissions, outages, restrictions, or policy changes.",
                "10.3 Your use of third-party services may be subject to their own separate terms and policies.",
                "10.4 Nothing in these Terms makes you a contractual counterparty of a third-party carrier unless that is expressly stated.",
            ],
        },
        {
            type: "text",
            title: "11. Intellectual Property Rights",
            bullets: [
                "11.1 All intellectual property rights in the Service, including its software, design, branding, text, graphics, databases, structure, plan presentation, and underlying systems, are owned by us or licensed to us.",
                "11.2 Subject to your compliance with these Terms and completion of the relevant payment, we grant you a limited, revocable, non-exclusive, non-transferable, non-sublicensable licence to use the Service and any delivered plan materials for your personal, lawful, non-commercial use only.",
                "11.3 Unless we expressly agree otherwise in writing, you must not:",
                "(a) reproduce, publish, distribute, resell, sublicense, or commercially exploit any part of the Service;",
                "(b) remove proprietary notices;",
                "(c) share or publish QR codes, activation codes, or installation details except for your own personal use of the purchased eSIM Plan; or",
                "(d) create derivative commercial offerings based on the Service.",
                "11.4 You retain ownership of materials you lawfully submit to the Service, but you grant us a non-exclusive, worldwide, royalty-free licence to host, store, reproduce, adapt, and process such materials as reasonably necessary to operate, secure, maintain, and improve the Service, subject to applicable law and our Privacy Policy.",
            ],
        },
        {
            type: "text",
            title: "12. Service Availability and Technical Issues",
            bullets: [
                "12.1 We do not guarantee that the Service will be uninterrupted, error-free, or available at all times.",
                "12.2 We may perform maintenance, updates, security actions, moderation actions, supplier changes, or technical interventions that temporarily affect access to the Service.",
                "12.3 We are not responsible for interruptions, delays, or failures caused by internet outages, device issues, browser issues, software conflicts, email delivery filtering, force majeure events, local network restrictions, government actions, or failures of third-party providers outside our reasonable control.",
                "12.4 If delivery or activation fails due to a technical issue attributable to us, we may, at our discretion, re-deliver the eSIM, correct the issue, restore the relevant Tokens, replace the plan, or otherwise provide an appropriate remedy.",
            ],
        },
        {
            type: "text",
            title: "13. Warranties and Disclaimers",
            bullets: [
                "13.1 We warrant that we are entitled to operate the Service and grant the rights expressly stated in these Terms.",
                "13.2 Except as expressly provided in these Terms and to the fullest extent permitted by law, the Service and all eSIM Plans are provided on an “as is” and “as available” basis.",
                "13.3 We do not guarantee:",
                "(a) that every plan will meet your individual expectations or travel requirements;",
                "(b) that every destination will have uninterrupted service in every area;",
                "(c) that every Supported Device will perform identically;",
                "(d) that speeds, latency, or network technology will remain constant; or",
                "(e) uninterrupted access to the Service.",
            ],
        },
        {
            type: "text",
            title: "14. Limitation of Liability",
            bullets: [
                "14.1 Nothing in these Terms excludes or limits liability where such exclusion or limitation is prohibited by law, including liability for death or personal injury caused by negligence, fraud, fraudulent misrepresentation, or any other liability that cannot lawfully be excluded.",
                "14.2 Subject to clause 14.1, our total aggregate liability arising out of or in connection with the Service, any Order, or these Terms shall not exceed the total amount actually paid by you to us through the Service during the 12 months preceding the event giving rise to the claim.",
                "14.3 Subject to clause 14.1, we shall not be liable for any indirect, incidental, special, consequential, or punitive loss, or for any loss of profit, revenue, business, goodwill, opportunity, anticipated savings, or data.",
                "14.4 Subject to clause 14.1, we are not liable for losses arising from:",
                "(a) device incompatibility or network lock issues on your side;",
                "(b) incorrect destination or plan selection made by you;",
                "(c) premature activation, incorrect installation, or deletion of the eSIM by you;",
                "(d) roaming charges or other fees imposed by your own mobile carrier; or",
                "(e) third-party carrier outages or coverage limitations beyond our reasonable control.",
                "14.5 If you are a consumer, this clause does not affect rights that cannot be waived or limited under mandatory consumer law.",
            ],
        },
        {
            type: "text",
            title: "15. Indemnity",
            bullets: [
                "15.1 To the extent permitted by law, you agree to indemnify and hold harmless the Company and its directors, officers, employees, contractors, and agents from and against claims, losses, liabilities, damages, and reasonable costs arising out of or connected with:",
                "(a) your breach of these Terms;",
                "(b) your unlawful or improper use of the Service;",
                "(c) your infringement of third-party rights; or",
                "(d) false, unlawful, or misleading information submitted by you.",
            ],
        },
        {
            type: "text",
            title: "16. Privacy and Data Protection",
            bullets: [
                "16.1 We process personal data in accordance with our Privacy Policy and applicable data protection law, including the UK GDPR and the Data Protection Act 2018.",
                "16.2 By using the Service, you acknowledge that your personal data may be processed for account administration, payment handling, service delivery, identity and fraud checks, support, security, legal compliance, and related legitimate business purposes as described in our Privacy Policy.",
            ],
        },
        {
            type: "text",
            title: "17. Suspension and Termination",
            bullets: [
                "17.1 We may suspend, restrict, or terminate your access to the Service or your Account with immediate effect where reasonably necessary, including where:",
                "(a) you breach these Terms;",
                "(b) we suspect fraud, abuse, or unlawful activity;",
                "(c) your conduct creates security, legal, operational, supplier, or reputational risk;",
                "(d) payment has been reversed or is under dispute; or",
                "(e) we are required to do so by law or by a competent authority.",
                "17.2 We may suspend delivery of eSIM Plans while investigating suspected abuse, chargeback activity, unauthorised payments, or materially inaccurate user information.",
                "17.3 Suspension or termination does not affect rights, remedies, or obligations that accrued before the date of suspension or termination.",
                "17.4 Clauses that by their nature should survive termination will continue in force, including clauses concerning payment, refunds, liability, intellectual property, dispute resolution, and data protection.",
            ],
        },
        {
            type: "text",
            title: "18. Changes to the Terms",
            bullets: [
                "18.1 We may update these Terms from time to time for legal, regulatory, technical, supplier-related, commercial, or operational reasons.",
                "18.2 The most current version will be published on the Service with the revised effective date.",
                "18.3 Where changes are material, we may provide additional notice by email, through your Account, or on the website.",
                "18.4 Your continued use of the Service after the updated Terms take effect constitutes acceptance of the revised Terms.",
            ],
        },
        {
            type: "text",
            title: "19. Notices",
            bullets: [
                "19.1 Notices to us must be sent to info@ariessim.co.uk, unless we specify another contact method.",
                "19.2 We may send notices to you using the email address associated with your Account, by in-service notification, or by posting notice on the Service.",
            ],
        },
        {
            type: "text",
            title: "20. Governing Law and Jurisdiction",
            bullets: [
                "20.1 These Terms and any non-contractual obligations arising out of or in connection with them shall be governed by the laws of England and Wales.",
                "20.2 If you are acting in the course of business, the courts of England and Wales shall have exclusive jurisdiction over any dispute arising out of or in connection with these Terms.",
                "20.3 If you are a consumer, nothing in these Terms deprives you of any mandatory protections granted by the laws of your country of habitual residence where such protections apply and cannot be excluded by contract.",
                "20.4 Consumer disputes may also be resolved through applicable out-of-court consumer dispute mechanisms where required or permitted by law.",
            ],
        },
        {
            type: "text",
            title: "21. Miscellaneous",
            bullets: [
                "21.1 If any provision of these Terms is found invalid, illegal, or unenforceable, the remaining provisions shall remain in full force and effect.",
                "21.2 Our delay or failure to enforce any provision of these Terms shall not constitute a waiver of that provision or any other right.",
                "21.3 You may not assign, transfer, or otherwise dispose of your rights or obligations under these Terms without our prior written consent.",
                "21.4 We may assign or transfer our rights and obligations in connection with a merger, acquisition, restructuring, business transfer, or sale of assets.",
                "21.5 These Terms, together with any policies expressly referenced in them, constitute the entire agreement between you and us regarding the Service and supersede prior discussions or understandings relating to the same subject matter.",
            ],
        },
        {
            type: "text",
            title: "22. Contact Details",
            bullets: [
                "ARIES ACCESSIBILITY LTD",
                "Company Number: 15588986",
                "Address: 20 Wenlock Road, London, England, N1 7GU",
                "Email: info@ariessim.co.uk",
                "Phone: +44 7418 636626",
            ],
        },
    ],
};

export default termsSchema;